version: '3'
services:
  db:
    image: mysql:5.7
    container_name: danubio_mysql
    restart: always
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env.dev
    ports:
      - "3306:3306"
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: danubio_backend
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
volumes:
  data: