# Generated by Django 2.2 on 2024-01-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_ammount',
            field=models.IntegerField(default=0),
        ),
    ]
